version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: invently
      POSTGRES_USER: invently_user
      POSTGRES_PASSWORD: invently_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U invently_user -d invently"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: